image: ruby:2.4.2

stages:
  - create_infra
  - dns_records
  - deploy_stack


variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'


build_job:
  stage: build
  script:
    - echo 'this section is empry now.. plz come back later :)'
  tags:
    - gitlab-org
  when: manual


create_dns_record:
  stage: dns_records
  script:
    - echo 'echo 'this section is empry now.. plz come back later :)
  tags:
    - loadbalancer
  when: manual


compose_etcd:
  stage: deploy_stack
  script:
    - cd 3_stack
    - ls -la
    - docker stack deploy -c 1_compose-etcd.yml etcd
  tags:
    - loadbalancer
  when: manual





