version: "3.3"

networks:
  default:
    external:
      name: traefik_network

volumes:
    prometheus: 
    grafana: {}

# configs:

#   node_rules:
#     file: ./prometheus/rules/swarm_node.rules.yml
#   task_rules:
#     file: ./prometheus/rules/swarm_task.rules.yml

services:
  dockerd-exporter:
    image: stefanprodan/caddy
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  cadvisor:
    image: google/cadvisor
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  grafana:
    image: stefanprodan/swarmprom-grafana:5.3.4
    environment:
      - GF_SECURITY_ADMIN_USER=ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD=ADMIN_PASSWORD
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana:/var/lib/grafana
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.basic.frontend.rule=Host:grafana.ozyab.tk"
        - "traefik.basic.port=3000"
        - "traefik.basic.protocol=http" 
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M


  node-exporter:
    image: stefanprodan/swarmprom-node-exporter:v0.16.0
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  prometheus:
    image: stefanprodan/swarmprom-prometheus:v2.5.0
    command:
      - '--config.file=/etc/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=24h'
    volumes:
      - prometheus:/prometheus
      - /opt/prometheus/prometheus.yml:/etc/prometheus.yml:ro  #directory on node

    # configs:
    #   - source: node_rules
    #     target: /etc/prometheus/swarm_node.rules.yml
    #   - source: task_rules
    #     target: /etc/prometheus/swarm_task.rules.yml

    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.basic.frontend.rule=Host:prometheus.ozyab.tk"
        - "traefik.basic.port=9090"
        - "traefik.basic.protocol=http"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.node == worker-02
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M
