version: "3.4"
services:
  traefik_init:
    image: traefik:1.5
    env_file:
      - variables.env
    command:
      - storeconfig
      - --api
      - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entrypoints=Name:https Address::443 TLS
      - --defaultentrypoints=http,https
      - --acme
      - --acme.storage=traefik/acme/account
      - --acme.entryPoint=https
      - --acme.httpChallenge.entryPoint=http
      - --acme.onHostRule=true
      - --acme.onDemand=false
      - --acme.email=692677@mail.ru
      - --docker
      - --docker.swarmMode
      - --docker.domain=ozyab.tk
      - --docker.watch
      - --docker.exposedbydefault=false
      - --docker.endpoint=unix:///var/run/docker.sock
      - --etcd
      - --etcd.endpoint=etcd0:2379,etcd1:2379,etcd2:2379
      - --etcd.watch=true
      - --etcd.prefix=/traefik
ersion: "3.4"
services:
  traefik_init:
    image: traefik:1.5
    env_file:
      - variables.env
    command:
      - storeconfig
      - --api
      - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entrypoints=Name:https Address::443 TLS
      - --defaultentrypoints=http,https
      - --acme
      - --acme.storage=traefik/acme/account
      - --acme.entryPoint=https
      - --acme.httpChallenge.entryPoint=http
      - --acme.onHostRule=true
      - --acme.onDemand=false
      - --acme.email=692677@mail.ru
      - --docker
      - --docker.swarmMode
      - --docker.domain=ozyab.tk
      - --docker.watch
      - --docker.exposedbydefault=false
      - --docker.endpoint=unix:///var/run/docker.sock
      - --etcd
      - --etcd.endpoint=etcd0:2379,etcd1:2379,etcd2:2379
      - --etcd.watch=true
      - --etcd.prefix=/traefik
      - --etcd.useAPIV3=true
      # - "--traefik.docker.network=traefik_network"
    networks:
      - traefik_network
    deploy:
      restart_policy:
        condition: on-failure
  traefik:
    image: traefik:1.5
    depends_on:
      - traefik_init
    command:
      - --etcd
      - --etcd.endpoint=etcd0:2379,etcd1:2379,etcd2:2379
      - --etcd.watch=true
      - --etcd.prefix=/traefik
      - --etcd.useAPIV3=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik_network
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  
networks:
  traefik_network:
    driver: overlay
    external: true
